[package]
name = "rupse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.4"
goblin = "0.6.1"
colored = "2.1.0"
iced-x86 = "1.21.0"